from app.core.config import Settings
from app.repositories.sqlite_model_repository import SQLiteValuationModelRepository
from app.schemas.dcf import (
    DcfAssumptions,
    MarginInput,
    NwcInput,
    RevenueGrowthInput,
    RevenueLinkedSeriesInput,
)
from app.schemas.models import SavedModelCreateRequest


def seed_demo_models(settings: Settings) -> None:
    repository = SQLiteValuationModelRepository(settings)
    if repository.count_models() > 0:
        return

    for model in demo_models():
        repository.create_model(model)


def demo_models() -> list[SavedModelCreateRequest]:
    return [
        SavedModelCreateRequest(
            name="Vertex Cloud",
            description="High-growth SaaS example with three operating leverage scenarios.",
            default_scenario="base",
            scenarios=[
                _scenario(
                    company_name="Vertex Cloud",
                    model_name="Vertex Cloud",
                    scenario_name="bear",
                    current_revenue=420.0,
                    revenue_growth=0.12,
                    target_margin=0.18,
                    discount_rate=0.11,
                    terminal_growth_rate=0.03,
                    current_market_price_per_share=22.0,
                ),
                _scenario(
                    company_name="Vertex Cloud",
                    model_name="Vertex Cloud",
                    scenario_name="base",
                    current_revenue=420.0,
                    revenue_growth=0.18,
                    target_margin=0.24,
                    discount_rate=0.1,
                    terminal_growth_rate=0.035,
                    current_market_price_per_share=22.0,
                ),
                _scenario(
                    company_name="Vertex Cloud",
                    model_name="Vertex Cloud",
                    scenario_name="bull",
                    current_revenue=420.0,
                    revenue_growth=0.24,
                    target_margin=0.29,
                    discount_rate=0.095,
                    terminal_growth_rate=0.04,
                    current_market_price_per_share=22.0,
                ),
            ],
        ),
        SavedModelCreateRequest(
            name="North River Industrials",
            description="Mature industrial company with steadier reinvestment and margin outcomes.",
            default_scenario="base",
            scenarios=[
                _scenario(
                    company_name="North River Industrials",
                    model_name="North River Industrials",
                    scenario_name="bear",
                    current_revenue=1800.0,
                    current_margin=0.14,
                    revenue_growth=0.03,
                    target_margin=0.145,
                    discount_rate=0.095,
                    terminal_growth_rate=0.022,
                    cash=160.0,
                    debt=520.0,
                    shares=94.0,
                    current_market_price_per_share=31.0,
                ),
                _scenario(
                    company_name="North River Industrials",
                    model_name="North River Industrials",
                    scenario_name="base",
                    current_revenue=1800.0,
                    current_margin=0.14,
                    revenue_growth=0.05,
                    target_margin=0.16,
                    discount_rate=0.09,
                    terminal_growth_rate=0.025,
                    cash=160.0,
                    debt=520.0,
                    shares=94.0,
                    current_market_price_per_share=31.0,
                ),
                _scenario(
                    company_name="North River Industrials",
                    model_name="North River Industrials",
                    scenario_name="bull",
                    current_revenue=1800.0,
                    current_margin=0.14,
                    revenue_growth=0.07,
                    target_margin=0.175,
                    discount_rate=0.085,
                    terminal_growth_rate=0.028,
                    cash=160.0,
                    debt=520.0,
                    shares=94.0,
                    current_market_price_per_share=31.0,
                ),
            ],
        ),
        SavedModelCreateRequest(
            name="Harbor Retail",
            description="Cyclical retailer with lower terminal growth and modest capital intensity.",
            default_scenario="base",
            scenarios=[
                _scenario(
                    company_name="Harbor Retail",
                    model_name="Harbor Retail",
                    scenario_name="bear",
                    current_revenue=950.0,
                    current_margin=0.08,
                    revenue_growth=0.01,
                    target_margin=0.075,
                    discount_rate=0.11,
                    terminal_growth_rate=0.015,
                    cash=80.0,
                    debt=190.0,
                    shares=42.0,
                    current_market_price_per_share=18.0,
                ),
                _scenario(
                    company_name="Harbor Retail",
                    model_name="Harbor Retail",
                    scenario_name="base",
                    current_revenue=950.0,
                    current_margin=0.08,
                    revenue_growth=0.03,
                    target_margin=0.09,
                    discount_rate=0.102,
                    terminal_growth_rate=0.02,
                    cash=80.0,
                    debt=190.0,
                    shares=42.0,
                    current_market_price_per_share=18.0,
                ),
                _scenario(
                    company_name="Harbor Retail",
                    model_name="Harbor Retail",
                    scenario_name="bull",
                    current_revenue=950.0,
                    current_margin=0.08,
                    revenue_growth=0.05,
                    target_margin=0.1,
                    discount_rate=0.095,
                    terminal_growth_rate=0.022,
                    cash=80.0,
                    debt=190.0,
                    shares=42.0,
                    current_market_price_per_share=18.0,
                ),
            ],
        ),
    ]


def _scenario(
    company_name: str,
    model_name: str,
    scenario_name: str,
    current_revenue: float,
    revenue_growth: float,
    target_margin: float,
    discount_rate: float,
    terminal_growth_rate: float,
    current_margin: float = 0.12,
    tax_rate: float = 0.24,
    cash: float = 120.0,
    debt: float = 40.0,
    shares: float = 50.0,
    current_market_price_per_share: float = 20.0,
) -> DcfAssumptions:
    return DcfAssumptions(
        company_name=company_name,
        model_name=model_name,
        scenario_name=scenario_name,
        model_type="fcff",
        currency_symbol="$",
        current_revenue=current_revenue,
        current_ebit_margin=current_margin,
        tax_rate=tax_rate,
        forecast_years=5,
        revenue_growth=RevenueGrowthInput(mode="constant", constant_rate=revenue_growth),
        margin_assumptions=MarginInput(mode="interpolate", target_margin=target_margin),
        dna_assumptions=RevenueLinkedSeriesInput(mode="percent", percent_of_revenue=0.025),
        capex_assumptions=RevenueLinkedSeriesInput(mode="percent", percent_of_revenue=0.04),
        nwc_assumptions=NwcInput(mode="percent", percent_of_incremental_revenue=0.015),
        stock_based_compensation=RevenueLinkedSeriesInput(mode="percent", percent_of_revenue=0.01),
        net_operating_losses=0.0,
        discount_rate=discount_rate,
        mid_year_discounting=True,
        terminal_value_method="gordon_growth",
        terminal_growth_rate=terminal_growth_rate,
        cash=cash,
        debt=debt,
        preferred_equity=0.0,
        minority_interest=0.0,
        diluted_shares_outstanding=shares,
        current_market_price_per_share=current_market_price_per_share,
        margin_of_safety=0.2,
    )
