from typing import Protocol

from app.schemas.models import SavedModelCreateRequest, SavedModelUpdateRequest, SavedValuationModel


class ValuationModelRepository(Protocol):
    def count_models(self) -> int: ...

    def list_models(self) -> list[SavedValuationModel]: ...

    def get_model(self, model_id: str) -> SavedValuationModel | None: ...

    def create_model(self, payload: SavedModelCreateRequest) -> SavedValuationModel: ...

    def update_model(self, model_id: str, payload: SavedModelUpdateRequest) -> SavedValuationModel | None: ...

    def delete_model(self, model_id: str) -> bool: ...

    def duplicate_model(self, model_id: str) -> SavedValuationModel | None: ...

